GET http://localhost:3001/api/persons

###

DELETE http://localhost:3001/api/persons/1

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Fania Kasereka",
    "number": "040-243563"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Fanisa Kasereka",
    "number": "040-243563"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Fania Kase",
    "number": "040-243563"
}

###
DELETE http://localhost:3001/api/persons/3562

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Fania Kaserek",
    "number": "040-243563"
}

### malformed id → 400 "malformatted id"
GET http://localhost:3001/api/persons/not-a-real-id

### well-formed but non-existent id → 404
GET http://localhost:3001/api/persons/6a0b0933deb4cb5214ab8c00

###
DELETE http://localhost:3001/api/persons/8605

###
DELETE http://localhost:3001/api/persons/365

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Mumbere Joel",
    "number": "0779204828"
}